export const MEDITATION_DATA = [
  {
    id: 1,
    title: "Mountains",
    image: "trees.webp",
    audio: "trees.mp3",
  },
  {
    id: 2,
    title: "Rivers",
    image: "river.webp",
    audio: "river.mp3",
  },
  {
    id: 3,
    title: "Sunset",
    image: "meditate-under-tree.webp",
    audio: "meditate-under-tree.mp3",
  },
  {
    id: 4,
    title: "Beaches",
    image: "beach.webp",
    audio: "beach.mp3",
  },
  {
    id: 5,
    title: "Starry Night",
    image: "yosemite-stars.webp",
    audio: "yosemite-stars.mp3",
  },
  {
    id: 6,
    title: "Waterfall",
    image: "waterfall.webp",
    audio: "waterfall.mp3",
  },
  {
    id: 7,
    title: "Firewood Burning",
    image: "firewood-burning.jpg",
    audio: "firewood-burning-sound.mp3",
  },
  {
    id: 8,
    title: "Birds Chirping",
    image: "birds-chirping.jpg",
    audio: "birds-chirping.mp3",
  },
  {
    id: 9,
    title: "UnderWater",
    image: "underwater.jpg",
    audio: "underwater-ambience.mp3",
  },
  {
    id: 10,
    title: "Thunderstorm",
    image: "thunderstorm.jpg",
    audio: "thunderstorm.mp3",
  },
  {
    id: 11,
    title: "Heavy Rain",
    image: "heavy-rain.jpg",
    audio: "heavy-rain.mp3",
  },
  {
    id: 12,
    title: "Wind Blowing",
    image: "wind-blowing.jpg",
    audio: "wind-blowing.mp3",
  },
  {
    id: 13,
    title: "Crickets Chirping",
    image: "night-cricket.jpg",
    audio: "night-cricket.mp3",
  },
];

export const AUDIO_FILES = {
  "trees.mp3": require("../../assets/meditation/audio/trees.mp3"),
  "river.mp3": require("../../assets/meditation/audio/river.mp3"),
  "meditate-under-tree.mp3": require("../../assets/meditation/audio/meditate-under-tree.mp3"),
  "beach.mp3": require("../../assets/meditation/audio/beach.mp3"),
  "yosemite-stars.mp3": require("../../assets/meditation/audio/yosemite-stars.mp3"),
  "waterfall.mp3": require("../../assets/meditation/audio/waterfall.mp3"),
  "firewood-burning-sound.mp3": require("../../assets/meditation/audio/firewood-burning-sound.mp3"),
  "birds-chirping.mp3": require("../../assets/meditation/audio/birds-chirping.mp3"),
  "underwater-ambience.mp3": require("../../assets/meditation/audio/underwater-ambience.mp3"),
  "thunderstorm.mp3": require("../../assets/meditation/audio/thunderstorm.mp3"),
  "heavy-rain.mp3": require("../../assets/meditation/audio/heavy-rain.mp3"),
  "wind-blowing.mp3": require("../../assets/meditation/audio/wind-blowing.mp3"),
  "night-cricket.mp3": require("../../assets/meditation/audio/night-cricket.mp3"),
};
